### ISSUE TITLE
Doppelte Einfärbung bei doppelten Regionen verhindern

### ISSUE THREAD

**Issue by hopsi** [tadwohlrapp/my-komoot-regions#1]
Regionen, die versehentlich doppelt in der Regionenliste stehen, werden auch doppelt eingefärbt und sind somit dunkler.
Ist das so gewollt? Finde ich eher unharmonisch.

**Comment by tadwohlrapp** [comment]
> Regionen, die versehentlich doppelt in der Regionenliste stehen

Ich wusste gar nicht, dass das möglich ist.

Du meinst aber nicht teilweise Überlagerung, also eine Einzelregion, die gleichzeitig Teil eines Regionen-Pakets ist? Also so wie hier:
![CleanShot 2024-03-01 at 22 54 27@2x](https://github.com/tadwohlrapp/my-komoot-regions/assets/2788192/1193cff0-0f7c-466e-b0b7-93b95c194b7a)

Könntest du n Screenshot deiner Karte posten, wo man die doppelte Einfärbung sieht, damit ich mir das besser vorstellen kann?

Und wenn du in deiner Browser-Konsole den folgenden Code eingibst, welcher die IDs aller von dir freigeschalteten Regionen ausgibt, erscheint da irgendeine der IDs doppelt bei dir?

`console.log(window.kmtBoot.getProps().packages.models.map(model => model.attributes.region.id).sort())`

**Comment by hopsi** [comment]
Doppelte Regionen gibt es, wenn über eine Aktion eine Region kostenlos verteilt wird, diese aber schon im Sammelalbum vorhanden ist.

Konsole:
`Array(101) [ 1196, 1298, 15206, 15220, 15308, 1601, 2002, 2003, 2005, 2006, … ]
​[0…99]
​​0: 1196
​​1: 1298
​​2: 15206
​​3: 15220
​​4: 15308
​​5: 1601
​​6: 2002
​​7: 2003
​​8: 2005
​​9: 2006
​​10: 2007
​​11: 2010
​​12: 2011
​​13: 2011`

Mindestens die letzte ist doppelt.

Screenshots anbei.

![komoot](https://github.com/tadwohlrapp/my-komoot-regions/assets/18510536/3673c74a-ed96-41bd-8c3b-27480b7f2352)
![komoot2](https://github.com/tadwohlrapp/my-komoot-regions/assets/18510536/e1df4b0d-7aa1-4305-9b00-1462900fb7a6)

Vermutlich müsste es reichen, über die Regionen sowas wie sort --unique laufen zu lassen. Oder das js-Äquivalent dazu.

**Comment by tadwohlrapp** [comment]
Stark, danke dir für die ausführliche Antwort!

Dann bin ich jetzt voll im Bilde weiß was zu tun ist.

Fix kommt demnächst 👍
